### ISSUE TITLE
SNMPCollector (snmp.py) not working at all

### ISSUE THREAD

**Issue by melsom** [BrightcoveOS/Diamond#474]
Hello,

I'm getting the following error running SNMPCollector: 

[2013-11-27 12:46:17,109] [MainThread] Unhandled exception: 'SNMPCollector' object has no attribute 'collect_snmp'
[2013-11-27 12:46:17,109] [MainThread] traceback: Traceback (most recent call last):
  File "/usr/bin/diamond", line 324, in main
    server.run()
  File "/usr/lib/pymodules/python2.7/diamond/server.py", line 340, in run
    self.schedule_collector(c)
  File "/usr/lib/pymodules/python2.7/diamond/server.py", line 272, in schedule_collector
    for name, schedule in c.get_schedule().items():
  File "/usr/share/diamond/collectors/snmp/snmp.py", line 86, in get_schedule
    schedule[task] = (self.collect_snmp, (device,
AttributeError: 'SNMPCollector' object has no attribute 'collect_snmp'

Seems to me that there is no function called "collect_snmp" defined anywhere in the source (snmp.py). It is present in snmpinterface.py, but it looks like it's not just a copy/paste to get it running. 

Our config:
enabled = True

path = switch
interval = 60
timeout = 5

[devices]

[[sw01]]
host = 172.0.0.1
port = 161
community = sw01-data

Could anyone help us getting this to work? :)

**Comment by fiona514** [comment]
me too, error message like 'AttributeError: 'SNMPCollector' object has no attribute 'collect_snmp'. still not working

**Comment by kormoc** [comment]
The code has moved to https://github.com/python-diamond/Diamond . Please try the current code there and if it's still an issue, please open a ticket there. Thanks!
