### ISSUE TITLE
Unhandled exception: 'server'

### ISSUE THREAD

**Issue by 7h3kk1d** [BrightcoveOS/Diamond#530]
I'm using FreeBSD 9.1 and after a while the process crashes and the log shows the following

```
[2014-02-07 11:15:22,837] [MainThread] Unhandled exception: 'server'
[2014-02-07 11:15:22,841] [MainThread] traceback: Traceback (most recent call last):
  File "/usr/local/bin/diamond", line 324, in main
    server.run()
  File "/usr/local/lib/python2.7/site-packages/diamond/server.py", line 333, in run
    self.mainloop()
  File "/usr/local/lib/python2.7/site-packages/diamond/server.py", line 402, in mainloop
    collectors_path = self.config['server']['collectors_path']
  File "build/bdist.freebsd-9.1-STABLE-amd64/egg/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'

```

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
