### ISSUE TITLE
GridEngineCollector -  ExpatError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by jnielsen7** [BrightcoveOS/Diamond#707]
qstat works and grid works simply by logging in. That is a user is not required to setup their environment to qsub, qstat, qalter, etc.

Configuration:
enabled = True
bin_path = /usr/bin/qstat
sge_root = /usr/share/gridengine

RHEL6
Linux dxhcpgrid-master 2.6.32-279.el6.x86_64 #1 SMP Wed Jun 13 18:24:36 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

diamond-3.4.602-0.noarch(built as of today)
gridengine-execd-6.2u5-10.el6.4.x86_64
gridengine-qmaster-6.2u5-10.el6.4.x86_64
gridengine-6.2u5-10.el6.4.x86_64
gridengine-qmon-6.2u5-10.el6.4.x86_64

[2014-08-11 15:02:19,196] [Thread-21146] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 412, in _run
    self.collect()
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 106, in collect
    self._collect_queue_stats()
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 116, in _collect_queue_stats
    parser = self.QueueStatsParser(output)
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 56, in __init__
    self.dom = xml.dom.minidom.parseString(document)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/minidom.py", line 1925, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/expatbuilder.py", line 942, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0

**Comment by jnielsen7** [comment]
This still appears to be an issue.

root@dxhcpgrid-master:/etc/diamond/collectors# rpm -qa | grep -i diamond
diamond-4.0.196-0.noarch


[2015-08-18 12:29:47,281] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 112, in collect
    self._collect_queue_stats()
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 122, in _collect_queue_stats
    parser = self.QueueStatsParser(output)
  File "/usr/share/diamond/collectors/gridengine/gridengine.py", line 56, in __init__
    self.dom = xml.dom.minidom.parseString(document.strip())
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/minidom.py", line 1925, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/expatbuilder.py", line 942, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0

**Comment by bradleyphipps** [comment]
@jnielsen7 Did you manage to fix this problem? Seems like Diamond is not picking up GridEngine env vars required to run qstat.

**Comment by jnielsen7** [comment]
@bradleyphipps I have not had time to revisit this. That might be it but it would seem odd that all other users on the system seem to have no issue finding and running the qstat command. Also if I make the diamond user accessible I can run qstat without the full path as well "which qstat" is found.

When I have time I will come back to it. What exactly was it you changed in the diamond.conf file?

**Comment by bradleyphipps** [comment]
@jnielsen7 It was just `. /etc/path/to/env_vars` at the start of the script stanza in `/etc/init/diamond.conf`. I think it would be cleaner to set/source them in `/etc/default/diamond`, but I haven't tested that yet.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
