### ISSUE TITLE
Strange bug in unit test

### ISSUE THREAD

**Issue by athoune** [BrightcoveOS/Diamond#749]
When I run

```
./test.py -v -c elasticsearch
```

I obtain this errors

```
======================================================================
ERROR: test_basic (testconvertor.TestConvertor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mlecarme/Developpement/bearstech/Diamond/src/diamond/test/testconvertor.py", line 9, in test_basic
    self.assertEquals(time.convert(60, 's', 'm'), 1.0)
  File "/Users/mlecarme/Developpement/bearstech/Diamond/lib/python2.7/site-packages/diamond/convertor.py", line 158, in convert
    return convertor.get(unit=newUnit)
  File "/Users/mlecarme/Developpement/bearstech/Diamond/lib/python2.7/site-packages/diamond/convertor.py", line 164, in get
    return self.do(unit=unit)
  File "/Users/mlecarme/Developpement/bearstech/Diamond/lib/python2.7/site-packages/diamond/convertor.py", line 177, in do
    raise NotImplementedError("unit %s" % unit)
NotImplementedError: unit m

======================================================================
FAIL: test_SetHostnameViaShellCmd (testcollector.BaseCollectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mlecarme/Developpement/bearstech/Diamond/src/diamond/test/testcollector.py", line 34, in test_SetHostnameViaShellCmd
    self.assertEquals('custom.localhost', c.get_hostname())
AssertionError: 'custom.localhost' != 'echo custom.localhost'
```

I don't understand the shell trick used to guess hostname.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
