### ISSUE TITLE
Starting diamond daemon showing this error in diamond log in ubuntu

### ISSUE THREAD

**Issue by akshayrawat618** [BrightcoveOS/Diamond#800]
[2015-02-09 00:13:43,318] [MainThread] Detaching Process.
[2015-02-09 00:13:43,736] [MainThread] Unhandled exception: [Errno 2] No such file or directory: '/storage/archive.log'
[2015-02-09 00:13:43,738] [MainThread] traceback: Traceback (most recent call last):
  File "/usr/bin/diamond", line 291, in main
    server.run()
  File "/usr/local/lib/python2.7/dist-packages/diamond/server.py", line 103, in run
    self.handlers = load_handlers(self.config, handlers)
  File "/usr/local/lib/python2.7/dist-packages/diamond/utils/classes.py", line 87, in load_handlers
    h = cls(handler_config)
  File "/usr/local/lib/python2.7/dist-packages/diamond/handler/archive.py", line 36, in **init**
    encoding=self.config['encoding']
  File "/usr/lib/python2.7/logging/handlers.py", line 171, in **init**
    BaseRotatingHandler.**init**(self, filename, 'a', encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 65, in **init**
    logging.FileHandler.**init**(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/**init**.py", line 897, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/storage/archive.log'

**Comment by jumping** [comment]
I have found the similar problem.

**Comment by akshayrawat618** [comment]
@jumping  There is a handler .conf  in /etc/diamond/handelrs/archivehandler.conf
   If you remove that it will work fine ,As in /etc/diamond/diamond.conf it is define so it will look there.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
