### ISSUE TITLE
Diamond start issue

### ISSUE THREAD

**Issue by harishva** [BrightcoveOS/Diamond#823]
[2015-07-07 22:46:19,407] [MainThread] Failed to load collector HttpdCollector
[2015-07-07 22:46:20,410] [MainThread] Failed to initialize Collector: DiskSpaceCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in **init**
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-07-07 22:46:20,410] [MainThread] Failed to load collector DiskSpaceCollector
[2015-07-07 22:46:20,410] [MainThread] Failed to initialize Collector: HttpdCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in **init**
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-07-07 22:46:20,411] [MainThread] Failed to load collector HttpdCollector

**Comment by hostingwalk** [comment]
Do you get this problem after diamond-setup  or after enabling HttpdCollector ?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
