### ISSUE TITLE
NetAppCollector incorrect argument list.

### ISSUE THREAD

**Issue by jnielsen7** [BrightcoveOS/Diamond#829]
The NetApp collector used to work on diamond 3.3 but appears to have stopped working on 4.0 (196 currently tested). Whenever the collector is enable I see the following in the diamond log.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
TypeError: collect() takes exactly 5 arguments (1 given)

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
