### ISSUE TITLE
BrightcoveOs/Diamond Libvirtkvm Collector is Not working In KVM Hypervisor 

### ISSUE THREAD

**Issue by MohamedHz** [BrightcoveOS/Diamond#843]
Hi,

I am trying to collect the metrics of  each instance cpu,memory,etc using the LibvirtKvm collectors and trying to store the metrics in opentsdb server. Unfortunately other collectors which I have tried was working fine.

For eg : Kvm,cpu,vmstats,memory etc.

But the LibvirtKvm collector was not working and we have noticed the python error on log file which mentioned below:

[2016-01-20 11:01:13,018] [MainThread] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/handler/Handler.py", line 74, in _process
    self.process(metric)
  File "/usr/lib/python2.6/site-packages/diamond/handler/tsdb.py", line 114, in process
    Collector=metric.getCollectorPath(),
  File "/usr/lib/python2.6/site-packages/diamond/metric.py", line 143, in getCollectorPath
    offset = self.path.index(self.host)
ValueError: substring not found

Could you please share your tips to resolve the problem. Thanks for  reading my post using your valuable time.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
