### ISSUE TITLE
Diamond not getting started 

### ISSUE THREAD

**Issue by vady1** [BrightcoveOS/Diamond#865]
Hi Guys
I got some issue with diamond
We are running a diamond collector to collect system metrics and show it on a graph. However, when I try to run the service using service diamond start, it will start but immediately get terminated. I tried to find the log. Syslog says init: diamond main process (32501) terminated with status 1
The following are the /etc/log/diamond/diamond.log
[2016-09-11 08:07:25,649] [MainThread] Can not find collector AppMetricCollector [2016-09-11 08:07:29,713] [MainThread] Collector failed! Traceback (most recent call last): File "/usr/lib/pymodules/python2.7/diamond/utils/scheduler.py", line 73, in collector_process collector._run() File "/usr/lib/pymodules/python2.7/diamond/collector.py", line 472, in _run self.collect() File "/usr/share/diamond/collectors/memory_docker/memory_docker.py", line 34, in collect for c in docker.Client().containers(all=True) File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 70, in containers res = self._result(self._get(u, params=params), True) File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner return f(self, args, kwargs) File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 120, in _get return self.get(url, self._set_request_timeout(kwargs)) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get return self.request('GET', url, kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request resp = self.send(prep, send_kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send r = adapter.send(request, *kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 453, in send raise ConnectionError(err, request=request) ConnectionError: ('Connection aborted.', error(2, 'No such file or directory')) [2016-09-11 08:07:33,719] [MainThread] Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory')) Traceback (most recent call last): File "/usr/share/diamond/collectors/docker_collector/docker_collector.py", line 67, in collect client = docker.Client(version='auto') File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 81, in init self._version = self._retrieve_server_version() File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 105, in _retrieve_server_version "diamond.log.2016-09-11" [readonly] 131088L, 9082758C 1,1 Top
Could you please help to debug?

Thank you .

**Comment by vady1** [comment]
One more detail: If i check status of the service by service diamond status it is stopped. However if i check with pu command there are many services running
oot     27371  0.1  0.6 156044 24976 ?        S    13:28   0:00 /usr/bin/python /usr/bin/diamond
root     27537  0.1  0.6 156044 24984 ?        S    13:29   0:00 /usr/bin/python /usr/bin/diamond
root     27592  0.1  0.6 156044 25044 ?        S    13:30   0:00 /usr/bin/python /usr/bin/diamond
root     27669  0.1  0.6 156044 24988 ?        S    13:30   0:00 /usr/bin/python /usr/bin/diamond
root     27680  0.0  0.6 156044 25100 ?        S    13:30   0:00 /usr/bin/python /usr/bin/diamond
root     27873  0.1  0.6 156044 24880 ?        S    13:31   0:00 /usr/bin/python /usr/bin/diamond
root     27881  0.1  0.6 156044 25020 ?        S    13:31   0:00 /usr/bin/python /usr/bin/diamond
root     27908  0.1  0.6 156300 25032 ?        S    13:31   0:00 /usr/bin/python /usr/bin/diamond
root     27994  0.1  0.6 156044 26488 ?        S    08:02   0:21 /usr/bin/python /usr/bin/diamond
root     28064  0.1  0.6 156304 25104 ?        S    13:32   0:00 /usr/bin/python /usr/bin/diamond
root     28225  0.1  0.6 156044 24892 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28226  0.1  0.6 156300 25512 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28236  0.1  0.6 156044 24892 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28238  0.1  0.6 156300 25108 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28252  0.0  0.6 156044 25164 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28270  0.1  0.6 156300 25184 ?        S    13:33   0:00 /usr/bin/python /usr/bin/diamond
root     28324  0.2  0.6 156044 24876 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28359  0.3  0.6 156044 24856 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28366  0.2  0.6 156300 25252 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28367  0.2  0.6 156300 25152 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28389  0.2  0.6 156044 24488 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28393  0.2  0.6 156300 24680 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28400  0.3  0.6 156300 24632 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28404  0.2  0.6 156300 24676 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond
root     28417  0.2  0.6 156044 24364 ?        S    13:34   0:00 /usr/bin/python /usr/bin/diamond

**Comment by r3cgm** [comment]
Hi vady1. Just a heads up, this repo was discontinued and ongoing efforts to develop Diamond have moved to this repo: https://github.com/python-diamond/Diamond
